# Generated by Django 4.2.5 on 2023-09-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='last_edit_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近编辑'),
        ),
    ]
