# Generated by Django 4.2.5 on 2023-09-27 15:18

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_last_edit_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=markdownx.models.MarkdownxField(verbose_name='正文'),
        ),
    ]
